import type { SettingsConfig } from "./types";

// Define default settings for all panels
export const defaultSettings: SettingsConfig = {
  panels: {
    // Geometry panel settings
    geometry: {
      id: "geometry",
      groups: [
        {
          id: "geometryType",
          label: "Geometry Type",
          settings: [
            {
              id: "geometryType",
              label: "Type",
              type: "select",
              options: [
                { label: "Plane", value: "plane" },
                { label: "Sphere", value: "sphere" },
                { label: "Cube", value: "cube" },
              ],
              defaultValue: "plane",
              description: "The type of geometry to render",
            },
          ],
        },
        {
          id: "planeSettings",
          label: "Plane Settings",
          settings: [
            {
              id: "planeWidth",
              label: "Width",
              type: "slider",
              min: 1,
              max: 10,
              step: 0.1,
              defaultValue: 3.8,
              description: "Width of the plane",
            },
            {
              id: "planeHeight",
              label: "Height",
              type: "slider",
              min: 1,
              max: 10,
              step: 0.1,
              defaultValue: 3.2,
              description: "Height of the plane",
            },
            {
              id: "planeSegments",
              label: "Segments",
              type: "slider",
              min: 1,
              max: 256,
              step: 1,
              defaultValue: 128,
              description: "Number of segments in the plane",
            },
          ],
        },
        {
          id: "sphereSettings",
          label: "Sphere Settings",
          settings: [
            {
              id: "sphereRadius",
              label: "Radius",
              type: "slider",
              min: 0.1,
              max: 5,
              step: 0.1,
              defaultValue: 1,
              description: "Radius of the sphere",
            },
            {
              id: "sphereWidthSegments",
              label: "Width Segments",
              type: "slider",
              min: 4,
              max: 128,
              step: 1,
              defaultValue: 32,
              description: "Number of width segments in the sphere",
            },
            {
              id: "sphereHeightSegments",
              label: "Height Segments",
              type: "slider",
              min: 4,
              max: 128,
              step: 1,
              defaultValue: 32,
              description: "Number of height segments in the sphere",
            },
          ],
        },
        {
          id: "cubeSettings",
          label: "Cube Settings",
          settings: [
            {
              id: "cubeSize",
              label: "Size",
              type: "slider",
              min: 0.1,
              max: 5,
              step: 0.1,
              defaultValue: 1,
              description: "Size of the cube",
            },
            {
              id: "cubeWidthSegments",
              label: "Width Segments",
              type: "slider",
              min: 1,
              max: 32,
              step: 1,
              defaultValue: 1,
              description: "Number of width segments in the cube",
            },
            {
              id: "cubeHeightSegments",
              label: "Height Segments",
              type: "slider",
              min: 1,
              max: 32,
              step: 1,
              defaultValue: 1,
              description: "Number of height segments in the cube",
            },
            {
              id: "cubeDepthSegments",
              label: "Depth Segments",
              type: "slider",
              min: 1,
              max: 32,
              step: 1,
              defaultValue: 1,
              description: "Number of depth segments in the cube",
            },
          ],
        },
        {
          id: "rotation",
          label: "Rotation",
          settings: [
            {
              id: "rotationX",
              label: "X Rotation",
              type: "slider",
              min: -Math.PI,
              max: Math.PI,
              step: 0.01,
              defaultValue: -1.1,
              description: "Rotation around the X axis",
            },
            {
              id: "rotationY",
              label: "Y Rotation",
              type: "slider",
              min: -Math.PI,
              max: Math.PI,
              step: 0.01,
              defaultValue: 0,
              description: "Rotation around the Y axis",
            },
            {
              id: "rotationZ",
              label: "Z Rotation",
              type: "slider",
              min: -Math.PI,
              max: Math.PI,
              step: 0.01,
              defaultValue: 0,
              description: "Rotation around the Z axis",
            },
          ],
        },
      ],
    },

    // Distortion panel settings
    distortion: {
      id: "distortion",
      groups: [
        {
          id: "normalNoise",
          label: "Normal Noise",
          settings: [
            {
              id: "normalNoiseScaleX",
              label: "Scale X",
              type: "slider",
              min: 0,
              max: 10,
              step: 0.1,
              defaultValue: 1.7,
              description: "Scale of the normal noise in the X direction",
            },
            {
              id: "normalNoiseScaleY",
              label: "Scale Y",
              type: "slider",
              min: 0,
              max: 10,
              step: 0.1,
              defaultValue: 3.5,
              description: "Scale of the normal noise in the Y direction",
            },
            {
              id: "normalNoiseSpeed",
              label: "Speed",
              type: "slider",
              min: 0,
              max: 1,
              step: 0.01,
              defaultValue: 0.08,
              description: "Speed of the normal noise animation",
            },
            {
              id: "normalNoiseStrength",
              label: "Strength",
              type: "slider",
              min: 0,
              max: 1,
              step: 0.01,
              defaultValue: 0.15,
              description: "Strength of the normal noise effect",
            },
          ],
        },
        {
          id: "normalNoiseShift",
          label: "Normal Noise Shift",
          collapsible: true,
          defaultCollapsed: true,
          settings: [
            {
              id: "normalNoiseShiftX",
              label: "Shift X",
              type: "slider",
              min: -1,
              max: 1,
              step: 0.01,
              defaultValue: 0,
              description: "Shift of the normal noise in the X direction",
            },
            {
              id: "normalNoiseShiftY",
              label: "Shift Y",
              type: "slider",
              min: -1,
              max: 1,
              step: 0.01,
              defaultValue: 0,
              description: "Shift of the normal noise in the Y direction",
            },
            {
              id: "normalNoiseShiftSpeed",
              label: "Shift Speed",
              type: "slider",
              min: 0,
              max: 1,
              step: 0.01,
              defaultValue: 0,
              description: "Speed of the normal noise shift animation",
            },
          ],
        },
        {
          id: "colorNoise",
          label: "Color Noise",
          settings: [
            {
              id: "colorNoiseScale",
              label: "Scale",
              type: "slider",
              min: 0,
              max: 10,
              step: 0.1,
              defaultValue: 2.0,
              description: "Scale of the color noise",
            },
            {
              id: "colorNoiseSpeed",
              label: "Speed",
              type: "slider",
              min: 0,
              max: 1,
              step: 0.01,
              defaultValue: 0.3,
              description: "Speed of the color noise animation",
            },
          ],
        },
        {
          id: "gradientShift",
          label: "Gradient Shift",
          settings: [
            {
              id: "gradientShiftX",
              label: "Shift X",
              type: "slider",
              min: -1,
              max: 1,
              step: 0.01,
              defaultValue: 0.2,
              description: "Shift of the gradient in the X direction",
            },
            {
              id: "gradientShiftY",
              label: "Shift Y",
              type: "slider",
              min: -1,
              max: 1,
              step: 0.01,
              defaultValue: 0.1,
              description: "Shift of the gradient in the Y direction",
            },
            {
              id: "gradientShiftSpeed",
              label: "Shift Speed",
              type: "slider",
              min: 0,
              max: 1,
              step: 0.01,
              defaultValue: 0.05,
              description: "Speed of the gradient shift animation",
            },
          ],
        },
      ],
    },

    // Colors panel settings
    colors: {
      id: "colors",
      groups: [
        {
          id: "gradientMode",
          label: "Gradient Mode",
          settings: [
            {
              id: "gradientMode",
              label: "Mode",
              type: "select",
              options: [
                { label: "B-spline", value: 0 },
                { label: "Linear", value: 1 },
                { label: "Step", value: 2 },
                { label: "Smooth step", value: 3 },
                { label: "Direct mapping", value: 4 },
              ],
              defaultValue: 0,
              description: "The interpolation mode for the gradient",
            },
          ],
        },
        {
          id: "colors",
          label: "Colors",
          settings: [
            {
              id: "color1",
              label: "Color 1",
              type: "color",
              defaultValue: "#ffffff",
              description: "First color in the gradient",
            },
            {
              id: "color2",
              label: "Color 2",
              type: "color",
              defaultValue: "#ffffff",
              description: "Second color in the gradient",
            },
            {
              id: "color3",
              label: "Color 3",
              type: "color",
              defaultValue: "#ffffff",
              description: "Third color in the gradient",
            },
            {
              id: "color4",
              label: "Color 4",
              type: "color",
              defaultValue: "#ffffff",
              description: "Fourth color in the gradient",
            },
          ],
        },
        {
          id: "background",
          label: "Background",
          settings: [
            {
              id: "backgroundColor",
              label: "Background Color",
              type: "color",
              defaultValue: "#fcfcfc",
              description: "Background color of the scene",
            },
          ],
        },
      ],
    },

    // Lighting panel settings
    lighting: {
      id: "lighting",
      groups: [
        {
          id: "lighting",
          label: "Lighting",
          settings: [
            {
              id: "lightX",
              label: "X",
              type: "slider",
              min: -1,
              max: 1,
              step: 0.01,
              defaultValue: 0.5,
              description: "X position of the light",
            },
            {
              id: "lightY",
              label: "Y",
              type: "slider",
              min: -1,
              max: 1,
              step: 0.01,
              defaultValue: 0.5,
              description: "Y position of the light",
            },
            {
              id: "lightZ",
              label: "Z",
              type: "slider",
              min: -1,
              max: 1,
              step: 0.01,
              defaultValue: 0.5,
              description: "Z position of the light",
            },
            {
              id: "lightDiffuse",
              label: "Diffuse",
              type: "slider",
              min: 0,
              max: 1,
              step: 0.01,
              defaultValue: 0.8,
              description: "Diffuse lighting intensity",
            },
            {
              id: "lightAmbient",
              label: "Ambient",
              type: "slider",
              min: 0,
              max: 1,
              step: 0.01,
              defaultValue: 0.2,
              description: "Ambient lighting intensity",
            },
            {
              id: "lightRim",
              label: "Rim",
              type: "slider",
              min: 0,
              max: 1,
              step: 0.01,
              defaultValue: 0.5,
              description: "Rim lighting intensity",
            },
          ],
        },
      ],
    },

    // Camera panel settings
    camera: {
      id: "camera",
      groups: [
        {
          id: "cameraSettings",
          label: "Camera Settings",
          settings: [
            {
              id: "cameraDistance",
              label: "Distance",
              type: "slider",
              min: 0.1,
              max: 5,
              step: 0.1,
              defaultValue: 0.9,
              description: "Distance of the camera from the target",
            },
            {
              id: "cameraFov",
              label: "Field of View",
              type: "slider",
              min: 10,
              max: 100,
              step: 1,
              defaultValue: 30,
              description: "Field of view of the camera in degrees",
            },
          ],
        },
        {
          id: "cameraPosition",
          label: "Camera Position",
          collapsible: true,
          defaultCollapsed: true,
          settings: [
            {
              id: "cameraPosX",
              label: "X Position",
              type: "slider",
              min: -5,
              max: 5,
              step: 0.1,
              defaultValue: 0,
              description: "X position of the camera",
            },
            {
              id: "cameraPosY",
              label: "Y Position",
              type: "slider",
              min: -5,
              max: 5,
              step: 0.1,
              defaultValue: 0,
              description: "Y position of the camera",
            },
            {
              id: "cameraPosZ",
              label: "Z Position",
              type: "slider",
              min: -5,
              max: 5,
              step: 0.1,
              defaultValue: 2,
              description: "Z position of the camera",
            },
          ],
        },
        {
          id: "cameraTarget",
          label: "Camera Target",
          collapsible: true,
          defaultCollapsed: true,
          settings: [
            {
              id: "cameraTargetX",
              label: "X Target",
              type: "slider",
              min: -5,
              max: 5,
              step: 0.1,
              defaultValue: 0,
              description: "X position of the camera target",
            },
            {
              id: "cameraTargetY",
              label: "Y Target",
              type: "slider",
              min: -5,
              max: 5,
              step: 0.1,
              defaultValue: 0,
              description: "Y position of the camera target",
            },
            {
              id: "cameraTargetZ",
              label: "Z Target",
              type: "slider",
              min: -5,
              max: 5,
              step: 0.1,
              defaultValue: 0,
              description: "Z position of the camera target",
            },
          ],
        },
      ],
    },

    // Presets panel settings
    presets: {
      id: "presets",
      groups: [
        {
          id: "presetButtons",
          label: "Presets",
          settings: [
            {
              id: "presetDefault",
              label: "Default",
              type: "button",
              buttonText: "Default",
              description: "Reset to default settings",
            },
            {
              id: "presetOceanWaves",
              label: "Ocean Waves",
              type: "button",
              buttonText: "Ocean Waves",
              description: "Apply ocean waves preset",
            },
            {
              id: "presetLavaFlow",
              label: "Lava Flow",
              type: "button",
              buttonText: "Lava Flow",
              description: "Apply lava flow preset",
            },
            {
              id: "presetAbstractArt",
              label: "Abstract Art",
              type: "button",
              buttonText: "Abstract Art",
              description: "Apply abstract art preset",
            },
          ],
        },
      ],
    },

    // Save panel settings
    save: {
      id: "save",
      groups: [
        {
          id: "saveOptions",
          label: "Save Options",
          settings: [
            {
              id: "transparentBackground",
              label: "Transparent Background",
              type: "toggle",
              defaultValue: false,
              description: "Save image with transparent background",
            },
            {
              id: "highQuality",
              label: "High Quality",
              type: "toggle",
              defaultValue: true,
              description: "Export image in high quality",
            },
            {
              id: "saveImage",
              label: "Save Image",
              type: "button",
              buttonText: "Save Image",
              variant: "primary",
              description: "Save the current view as an image",
            },
          ],
        },
      ],
    },

    // Code panel settings
    code: {
      id: "code",
      groups: [
        {
          id: "codeOptions",
          label: "Export Options",
          settings: [
            {
              id: "codeFormat",
              label: "Format",
              type: "select",
              options: [
                { label: "HTML", value: "html" },
                { label: "JavaScript", value: "js" },
                { label: "GLSL", value: "glsl" },
              ],
              defaultValue: "html",
              description: "Format of the exported code",
            },
            {
              id: "exportCode",
              label: "Export Code",
              type: "button",
              buttonText: "Export Code",
              variant: "primary",
              description: "Export the current shader as code",
            },
          ],
        },
      ],
    },
  },
};
